server:
  port: 9200
  address: 0.0.0.0

spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200
      username: elastic
      password: changeme

management:
  endpoints:
    web:
      exposure:
        include: "*"|